apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
  template:
    metadata: #Dessa linha para baixo será a config do Pod
      name: portal-noticias
      labels:
        app: portal-noticias #Esse valor vamos usar para vincular esse Pod a um ReplicaSet (usado lá no matchLabels)
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap  
  replicas: 3 #Define a quantidade de replcias que queremos do Pod's
  selector:
    matchLabels:
      app: portal-noticias #Aqui estou vinculando o ReplicaSet a um Pod cujo label desse Pod será app: portal-noticias



