apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-configmap
data:
  HOST_DB: svc-db-noticias:3306 #Queremos conversar com o Banco, podemos usar o nome do seu SVC ou IP do SVC
  USER_DB: root
  PASS_DB: q1w2e3r4
  DATABASE_DB: empresa
