apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80 # o targetPort: se ficar omitido será com o mesmo valor do port
      nodePort: 30001
  selector:
    app: sistema-noticias