apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80 # o targetPort: se ficar omitido será com o mesmo valor do port
      nodePort: 30000
  selector:
    app: portal-noticias