apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80 #Se eu deixar somente - port, o targetPort terá o mesmo valor
      nodePort: 30000
  selector:
    app: primeiro-pod