apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
    - port: 9000 #Indica que esse serviço ouve na 9000
      targetPort: 80 #Indica que vamos despachar na porta 80