apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-2
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: slow #Antes era stanrd pois usava o SC padrão do Cloud Provider, agora criamos o nosso SC chamado slow